# Generated by Django 4.2.7 on 2025-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
    ]
