# Generated by Django 4.2.7 on 2025-04-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_property_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('missed', 'Perdida'), ('busy', 'Ocupado'), ('failed', 'Fallida'), ('in-progress', 'En Progreso')], default='completed', max_length=20)),
                ('call_type', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], default='inbound', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='real_estate.property')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
