# Generated by Django 5.2 on 2025-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_propertycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
    ]
