# Generated by Django 5.2 on 2025-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_property_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible en búsqueda'),
        ),
    ]
